FROM oven/bun:1 AS build

WORKDIR /app

# Install dependencies
COPY package.json ./
RUN bun install

# Copy the project files and build the app
COPY . .
# RUN bun run build

# Serve the app with Bun's built-in server
# EXPOSE 3000

CMD ["bun", "run", "dev", "--", "--host"]
