concurrent = 2
check_interval = 3
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "srvwebstr01"
  url = "https://t-dev.epitest.eu"
  id = 1195
  token = "glrt-t3_iLNUb66ofgxVrpu73zxx"
  token_obtained_at = 2024-12-08T18:01:23Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:24.0.5"  # Base image for jobs
    privileged = false       # Not needed for host Docker
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]  # No need to repeat /var/run/docker.sock (handled by Docker Compose)
    shm_size = 0
    network_mtu = 0
